### ISSUE TITLE
Weird outcome for if:blank

### ISSUE THREAD

**Issue by misner** [blocknotes/activeadmin_dynamic_fields#1]
Hello,

Thanks for this wonderful gem that we really needed.

Our need was basic
- show field 1 and hide filed 2,3 and 4
- if user fills the field 1, show field 2, 3 and 4

So we used this:

```
f.has_many :steps,
                   allow_destroy: true,
                   heading:       false, 
                   new_record:    true,
                    do |step|
        
        step.input :field1,
          input_html: { data: { if: 'blank', action: 'hide', target: '.st_video_related' } }
      step.input :field2,
         wrapper_html: { class: 'st_video_related' }
      step.input :field3,
         wrapper_html: { class: 'st_video_related' }
      step.input :field4,
        wrapper_html: { class: 'st_video_related' }
```

We thought that when you say if = blank, then the targets will be hidden. But the outcome was the opposite we had expected. Field 2, 3 and 4 were 

- viewable when the field 1 was empty and 

- not viewable when the field 1 was filled

So we changed to the opposite: step.input :field1,
          input_html: { data: { if: 'not_blank', action: 'hide', target: '.st_video_related' } }

and now it works: all Steps where field 1 is empty have field 2,3 and 4 invisible

Did we misunderstand how the semantic works or is there something weird here? shouldn't we really put : input_html: { data: { if: 'blank', action: 'hide', target: '.st_video_related' } } ?

Thanks

**Comment by blocknotes** [comment]
Thank you for your comment @misner 

You are right, there's something wrong.

blank + hide is reversed
but checked + hide works as expected

 I need to do some checks.

**Comment by blocknotes** [comment]
@misner: I have just released a minor fix that should resolve the problem - can you do some tests please?

**Comment by misner** [comment]
Great. I will test this week end if possible, if not on Monday
Michael

**Comment by misner** [comment]
Just tested it. Works  fine now. thanks!

**Comment by blocknotes** [comment]
Good :)
