### ISSUE TITLE
How do I can run test?

### ISSUE THREAD

**Issue by inyerade** [blocknotes/activeadmin_dynamic_fields#10]
If I want to add a feature or correction and I whant to run test before a pull request. how can I do?

**Comment by blocknotes** [comment]
Hi @inyerade.

You can run the tests using:
`bin/rspec`
or
`bin/rake spec`

There was an issue related to _undefined method assets_ in Rails Application Configuration using recent dependencies. I fixed it recently adding to the gemspec:
`spec.add_development_dependency 'sprockets-rails', '~> 3.2'`

**Comment by blocknotes** [comment]
Closing because it should be addressed.
Please reopen it if more information are needed.
