### ISSUE TITLE
Uglifier issue

### ISSUE THREAD

**Issue by frobert** [blocknotes/activeadmin_dynamic_fields#14]
Hi, I'm getting this issue when preparing for production. Any idea?

gem 'uglifier', '>= 4.1'
added config.assets.js_compressor = Uglifier.new(harmony: true) to production.rb

<img width="640" alt="Screenshot 2022-03-08 at 16 46 58" src="https://user-images.githubusercontent.com/858426/157273662-50fc1040-122e-45fb-ac64-72ec207e56b5.png">

**Comment by blocknotes** [comment]
Hey @frobert, 
can you try pointing the gem to this branch `fix-evaluate-condition-data-if`?
Just to make a double check that it fixes the issue.

**Comment by frobert** [comment]
@blocknotes this fixes the issue, perfect! Thanks.

**Comment by blocknotes** [comment]
@frobert: good :)

I included this fix in the latest release 0.6.4
