### ISSUE TITLE
Support for activeadmin_addons (select2)

### ISSUE THREAD

**Issue by tsukaby** [blocknotes/activeadmin_dynamic_fields#23]
Hello.

I am using the following library.
https://github.com/platanus/activeadmin_addons

When using select2, activeadmin_dynamic_fields does not work.
I know it is difficult to be compatible with other 3rd party libraries, but it would be nice to be supported.

Thank you.

**Comment by blocknotes** [comment]
Hey @tsukaby,
I'm not familiar with _platanus/activeadmin_addons_

Can you share some code of the failing case and the expected result?

If they are using select2 it could be that the standard HTML select API is not available.
Consider that you can also use `"data-function": "some_select2_function"` to define a custom check method and/or trigger a custom effect with `"data-then": "callback some_function"`
