### ISSUE TITLE
How make checkbox with toggle fields?

### ISSUE THREAD

**Issue by StanZhuravlev** [blocknotes/activeadmin_dynamic_fields#4]
Hi!

I see this example for hide fields, if checkbox is set.
```rb
f.input :published, input_html: { data: { if: 'checked', action: 'hide', target: '.grp1' } }
```

But I need make a toggle set of fields depend checkbox: after toggle checkbox a few fields will show, and few is hide. Can I make this with activeadmin_dynamic_fields?

**Comment by dilmuhammad717** [comment]
@StanZhuravlev add '.grp1' class to all those items where you want to apply show hide on toggle checkbox.

**Comment by StanZhuravlev** [comment]
My question is misunderstanding. :( Once more: for example, I have a TWO set of fields with classes .grp1 and .grp2. And I want toggle a switch, and in one position all elements with class .grp1 are hides, but .grp2 are show. After next toggle, all elements with class .grp1 are show, but .grp2 are hide. 

Is it possible?

**Comment by blocknotes** [comment]
Sorry for replying so late @StanZhuravlev 😅 

You could setup the field to trigger a custom JS function (you can do mostly everything in this way):

```rb
f.input :published, input_html: { 'data-function': 'test_fun' }
```

```js
function test_fun(el) {
  $('.target1').toggleClass('active', el.is(':checked'))
  $('.target2').toggleClass('active', !el.is(':checked'))
}
```

In a future release I will also propose a syntax for else actions which could be useful in these situations.
